CLASS zresk_bp_mitarbeiter DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF ZRESK_R_Mitarbeiter.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zresk_bp_mitarbeiter IMPLEMENTATION.
ENDCLASS.


